### ISSUE TITLE
[대신증권.김윤중]카페 개설 안하시나요?

### ISSUE THREAD

**Issue by sosteam** [koscomopenapi/JsonSampleForJava#1]
흐흐 안녕하세요... 
대신증권 김윤중 과장입니다.
카페 개설 안하시나요?

**Comment by koscomopenapi** [comment]
안녕하세요? ^^

일단 github의 private repository를 하나 만들어두긴했습니다만...
github회원가입을 번거롭게 생각하시는 분이 계실듯하여 아직 공지는 안했습니다.

코스콤 김흥재

**Comment by sosteam** [comment]
TransactionHistory xml 파일 별로 첫 대문자 소문자 따로라 이거 맟줘 주시면 감사여.

**Comment by koscomopenapi** [comment]
네, 알겠습니다..^^

**Comment by koscomopenapi** [comment]
Java Class 정의 파일과 XML파일 변경해놨습니다.

감사합니다.
